name: Nuget push

defaults:
  run:
    working-directory: src
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Push
      run: dotnet push -s https://api.nuget.org/v3/index.json -k  ${{NUGET_TOKEN}} **/*.nupkg
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}